// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CampaignsList: typeof import('./src/components/CampaignsList.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
  }
}

export { }
