// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    CampaignList: typeof import('./src/components/CampaignList.vue')['default']
    CampaignProducts: typeof import('./src/components/CampaignProducts.vue')['default']
  }
}

export { }
